[package]
name = "ai-common"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
windows = { version = "0.60.0", features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation",
] }
