[package]
name = "yolov8"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
ndarray = "0.16.1"
ort = { git = "https://github.com/rede97/ort.git", branch = "ryzenai", features = ["load-dynamic"] }
ai-common = { path = "../ai-common" }
simplelog = "0.12.2"
log = "0.4.26"
clap = { version = "4.5", features = ["derive"] }
raqote = "0.8.5"
imageproc = "0.25.0"
ab_glyph = "0.2.29"
colored = "3.0.0"
gpu = "0.2.3"
wgpu = "24.0.1"
ffmpeg-next = "7.1.0"
ffmpeg-sys-next = "7.1.0"
anyhow = "1.0.97"
pollster = "0.4.0"
bytemuck = "1.22.0"
rayon = "1.10.0"
